<?php
$params = $this->params;
if (!count($params)) {
    return;
}
/** @var $param \WidRestApiDocumentator\ParamInterface */
$esc = $this->plugin('EscapeHtml');
?>
<div class="api-params">
    <h5><?= $esc($this->header) ?></h5>
    <table class="table table-bordered">
        <tr>
            <th class="span2">Name</th>
            <th class="span1">Type</th>
            <th class="span2">Value</th>
            <th>Description</th>
        </tr>
        <?php foreach($params as $param): ?>
            <tr class="<?= $param->isRequired() ? 'warning' : '' ?>">
                <td><?= $esc($param->getName()) ?></td>
                <td><?= $esc($param->getType()) ?></td>
                <td><?= sprintf('<input name="%s[%s]" class="api-param-value"/>', $this->namespace, $esc($param->getName())); ?></td>
                <td><span class="label label-important"><?= $param->isRequired() ? 'required' : '' ?></span> <?= $esc($param->getDescription()) ?></td>
            </tr>
        <?php endforeach; ?>
    </table>
</div>