<?php
$params = $this->params;
if (!count($params)) {
    return;
}
/** @var $param \WidRestApiDocumentator\ParamInterface */
$esc = $this->plugin('EscapeHtml');
?>
<div class="api-params">
    <h5><?= $esc($this->header) ?></h5>
    <table class="table table-bordered">
        <tr>
            <th class="span3">Name</th>
            <th class="span1">Type</th>
            <th class="span1">Required</th>
            <th>Description</th>
        </tr>
        <?php foreach($params as $param): ?>
            <tr>
                <td><?= $esc($param->getName()) ?></td>
                <td><?= $esc($param->getType()) ?></td>
                <td><?= $esc($param->isRequired() ? 'yes' : 'no') ?></td>
                <td><?= $esc($param->getDescription()) ?></td>
            </tr>
        <?php endforeach; ?>
    </table>
</div>