<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <?php
    echo $this->plugin('HeadTitle');
    echo $this->plugin('HeadMeta');
    echo $this->plugin('HeadLink');
    echo $this->plugin('HeadStyle');
    echo $this->plugin('HeadScript');
    ?>
</head>
<body>
<div class="container">
    <?= $this->content ?>
</div>
<a href="https://github.com/widmogrod/zf2-rest-api-documentator"><img style="position: absolute; top: 0; right: 0; border: 0;" src="https://s3.amazonaws.com/github/ribbons/forkme_right_darkblue_121621.png" alt="Fork me on GitHub"></a>
<?php echo $this->plugin('InlineScript'); ?>
</body>
</html>