<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <?php
    echo $this->plugin('HeadTitle');
    echo $this->plugin('HeadMeta');
    echo $this->plugin('HeadLink');
    echo $this->plugin('HeadStyle');
    echo $this->plugin('HeadScript');
    ?>
</head>
<body>
<div class="container">
    <?= $this->content ?>
</div>
<?php echo $this->plugin('InlineScript'); ?>
</body>
</html>